/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'pendingPartners' : bigint,
  'totalPartners' : bigint,
  'openTickets' : bigint,
  'netPaymentBalance' : number,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'sentAt' : bigint,
  'ticketId' : bigint,
  'senderRole' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'totalAmount' : number,
  'items' : string,
  'customerEmail' : string,
}
export interface Partner {
  'id' : bigint,
  'status' : string,
  'partnerName' : string,
  'submittedAt' : bigint,
  'email' : string,
  'storeName' : string,
  'storeDescription' : string,
  'category' : string,
}
export interface Payment {
  'id' : bigint,
  'direction' : string,
  'createdAt' : bigint,
  'reference' : string,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Ticket {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'subject' : string,
  'createdAt' : bigint,
  'customerEmail' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayment' : ActorMethod<[string, number, string, string, string], Payment>,
  'approvePartner' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeTicket' : ActorMethod<[bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[string, string, string, number], Order>,
  'createTicket' : ActorMethod<[string, string, string], Ticket>,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getPartner' : ActorMethod<[bigint], Partner>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTicket' : ActorMethod<[bigint], Ticket>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listPartners' : ActorMethod<[], Array<Partner>>,
  'listPayments' : ActorMethod<[], Array<Payment>>,
  'listTickets' : ActorMethod<[], Array<Ticket>>,
  'rejectPartner' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string, string], Message>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitPartner' : ActorMethod<
    [string, string, string, string, string],
    Partner
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];